version: "3"

tasks:
  stubs-deps:
    internal: true
    sources:
      - pyproject.toml
    cmds:
      - pip install '.[type]'

  generate-stubs:
    deps:
      - stubs-deps
    aliases:
      - stubs
    vars:
      STUB_DIR: type_stubs
    cmds:
      - stubgen --package dandy_lib --output {{ .STUB_DIR }} {{ .CLI_ARGS }}

  test:
    cmds:
      - tox -- {{ .CLI_ARGS }}

  debug:
    cmds:
      - tox -- --pdb {{ .CLI_ARGS }}

  type:
    cmds:
      - tox -e type -- {{ .CLI_ARGS }}
